# Generated by Django 3.2.19 on 2023-06-09 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housr_task1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communityevent',
            options={'permissions': [('view_event_name', 'Can view event name'), ('change_event_name', 'Can change event name'), ('delete_event_name', 'Can delete event name')]},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'permissions': [('view_employee_name', 'Can view employee name'), ('change_employee_name', 'Can change employee name'), ('delete_employee_name', 'Can delete employee name')]},
        ),
        migrations.AlterModelOptions(
            name='resident',
            options={'permissions': [('view_resident_name', 'Can view resident name'), ('change_resident_name', 'Can change resident name'), ('delete_resident_name', 'Can delete resident name')]},
        ),
    ]
